spring:
  application:
    name: evidence-service
  datasource:
    url: jdbc:h2:mem:evidence_db;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: evidence-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: gov.va.evidence.events
    listener:
      missing-topics-fatal: false
    admin:
      fail-fast: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    gov.va.evidence: INFO
  pattern:
    level: "%5p [traceId:%X{traceId}]"

server:
  error:
    include-message: always

app:
  kafka:
    topics:
      evidence-submitted: evidence-submitted-topic
