spring:
  application:
    name: evidence-service
  datasource:
    url: jdbc:h2:mem:evidence_db;DB_CLOSE_DELAY=-1;MODE=LEGACY
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,loggers
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    gov.va.evidence: INFO
  pattern:
    level: "%5p [traceId:%X{traceId}]"

server:
  error:
    include-message: always

